### ISSUE TITLE
Crash on Game Load

### ISSUE THREAD

**Issue by WenXin20** [coderbot16/Redwoods#3]
Forge v14.23.2815-1.12.2
Redwoods v1.0.0

I got this crash almost as soon as I launched the game.
Here's the [crash report](https://gist.github.com/WenXin20/50ac4c2315a71885e27c8ecbe3964885).

Also, could Dynamic Trees ever be supported?

**Comment by WenXin20** [comment]
Nevermind, just saw the hotfix.

**Comment by coderbot16** [comment]
Yeah, sorry about that. I thought I tested everything!

Also, I don't think that my trees would work well with Dynamic Trees since they're completely different from the types of trees that Dynamic Trees is meant to support. I imagine that something like https://minecraft.curseforge.com/projects/dynamic-trees-traverse-compat would be needed, but I don't think that it would be able to retain the look of Redwoods conifer trees.

**Comment by WenXin20** [comment]
Ok, that makes sense, and thanks.
